databases:
  - name: go-gin-db
    databaseName: go_gin_db
    user: mytestsite
    plan: standard

services:
  - type: web
    name: go-gin
    env: go
    buildCommand: "go build -tags netgo -ldflags '-s -w' -o app"
    startCommand: "./app"
    autoDeploy: false
    plan: standard
